const INITIAL_STEP = 0;
const HERE_INSTRUCTION_STEP = 1;
const SETTING_UP_TOKEN_AND_ID_STEP = 2;
const IS_IT_TOKEN_STEP = 3;
const TOKEN_SAVED_STEP = 4;
const ARTICLE_ID_SAVED_STEP = 5;
const IS_IT_ARTICLE_ID_STEP = 6;

module.exports = {
  INITIAL_STEP,
  HERE_INSTRUCTION_STEP,
  SETTING_UP_TOKEN_AND_ID_STEP,
  IS_IT_TOKEN_STEP,
  TOKEN_SAVED_STEP,
  ARTICLE_ID_SAVED_STEP,
  IS_IT_ARTICLE_ID_STEP,
};
